name: MinecraftGPT
main: it.ohalee.minecraftgpt.Main
version: 1.2.4
author: ohAlee
description: A Minecraft plugin that uses ChatGPT
api-version: 1.16
commands:
  chatgpt:
    description: A Minecraft plugin that uses ChatGPT
    aliases: [mcgpt, minecraftgpt]
libraries:
  - 'com.theokanning.openai-gpt3-java:client:0.8.1'
